import fs from 'fs/promises';import path from 'path';import sharp from 'sharp';import satori from 'satori';import {Resvg} from '@resvg/resvg-js';import {DEFAULT_DESIGN,Design} from './types';
function rgba(hex:string,a:number){const h=hex.replace('#','');const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16);return `rgba(${r},${g},${b},${a})`}
function valid(h:string){return /^#[0-9a-f]{6}$/i.test(h)}
async function autoColor(image:Buffer,darkening:number){try{const {data,info}=await sharp(image).resize(120,120,{fit:'cover',position:'top'}).raw().toBuffer({resolveWithObject:true});let r=0,g=0,b=0,n=0;for(let i=0;i<data.length;i+=info.channels){r+=data[i];g+=data[i+1];b+=data[i+2];n++}const f=Math.max(.35,1-darkening);return `#${Math.round(r/n*f).toString(16).padStart(2,'0')}${Math.round(g/n*f).toString(16).padStart(2,'0')}${Math.round(b/n*f).toString(16).padStart(2,'0')}`}catch{return '#17234a'}}
async function font(){return fs.readFile(path.join(process.cwd(),'public/assets/NotoSerifBengali-Bold.ttf'))}
function spans(text:string,phrases:string[]){const p=phrases.filter(Boolean).sort((a,b)=>b.length-a.length);if(!p.length)return text;const re=new RegExp(`(${p.map(x=>x.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')).join('|')})`,'g');const parts=text.split(re);return parts.map((x,i)=>p.includes(x)?{type:'span',props:{style:{color:'#ffd400'},children:x}}:x)}
export async function renderPoster(args:{image:Buffer;headline:string;subheadline:string;source:string;phrases:string[];design?:Partial<Design>;logo:'auto'|'light'|'dark'}){const d={...DEFAULT_DESIGN,...(args.design||{})};let shadow=d.shadow_color==='auto'?await autoColor(args.image,d.darkening):d.shadow_color;if(!valid(shadow))shadow='#17234a';const logoName=args.logo==='light'?'logo_light.png':args.logo==='dark'?'logo_dark.png':(shadow==='#fff'?'logo_dark.png':'logo_light.png');const logo=await fs.readFile(path.join(process.cwd(),'public/assets',logoName));const image64=args.image.toString('base64');const logo64=logo.toString('base64');const fontData=await font();const grad=d.composition==='image_first'?`linear-gradient(to top,${shadow} 0%,${rgba(shadow,.96)} 5%,${rgba(shadow,.72)} 11%,transparent ${Math.max(8,d.fade_length/27)}%)`:`linear-gradient(to bottom,${shadow} 0%,${rgba(shadow,.96)} 5%,${rgba(shadow,.72)} 11%,transparent ${Math.max(8,d.fade_length/27)}%)`;
const bottom=d.text_bottom;const headlineSize=d.headline_font_size||112;const subSize=d.subheadline_font_size||54;const headTop=d.composition==='image_first'?undefined:d.headline_top;const sourceTop=d.composition==='image_first'?undefined: d.source_top;
const tree:any={type:'div',props:{style:{width:2160,height:2700,display:'flex',position:'relative',overflow:'hidden',backgroundColor:shadow},children:[
{type:'img',props:{src:`data:image/jpeg;base64,${image64}`,style:{position:'absolute',left:0,top:0,width:2160,height:2700,objectFit:'cover'}}},
{type:'div',props:{style:{position:'absolute',inset:0,backgroundImage:grad}}},
{type:'div',props:{style:{position:'absolute',inset:0,backgroundColor:`rgba(0,0,0,${Math.max(0,Math.min(.35,d.darkening))})`}}},
{type:'div',props:{style:{position:'absolute',left:100,top:88,fontFamily:'Arial',fontSize:44,fontWeight:700,color:'#fff'},children:'sciencebee.com.bd'}},
{type:'img',props:{src:`data:image/png;base64,${logo64}`,style:{position:'absolute',right:d.logo_right,top:d.logo_top,width:d.logo_width,height:'auto'}}},
{type:'div',props:{style:{position:'absolute',left:1080+d.source_x-1080,top:sourceTop??(2700-bottom-d.headline_max_height-120),transform:'translateX(-50%)',padding:'16px 54px',borderRadius:60,backgroundColor:d.source_bg==='transparent'?'transparent':d.source_bg,color:'#fff',fontFamily:'SB',fontSize:d.source_font_size,fontWeight:700,whiteSpace:'nowrap'},children:`সোর্স: ${args.source}`}},
{type:'div',props:{style:{position:'absolute',left:1080+d.headline_x-d.headline_width/2,top:headTop??(2700-bottom-d.headline_max_height),width:d.headline_width,maxHeight:d.headline_max_height,display:'flex',flexDirection:'column',alignItems:'center',fontFamily:'SB',fontWeight:700,textAlign:'center',color:'#fff',textShadow:'0 3px 6px rgba(0,0,0,.28)'},children:[
{type:'div',props:{style:{fontSize:headlineSize,lineHeight:d.line_height,width:d.headline_width,display:'flex',justifyContent:'center'},children:spans(args.headline,args.phrases)}},
{type:'div',props:{style:{marginTop:d.subheadline_y,transform:`translateX(${d.subheadline_x}px)`,fontSize:subSize,lineHeight:d.line_height,width:d.subheadline_width,display:'flex',justifyContent:'center'},children:spans(args.subheadline,args.phrases)}}]}}
]}};
const svg=await satori(tree,{width:2160,height:2700,fonts:[{name:'SB',data:fontData,weight:700,style:'normal'}]});return Buffer.from(new Resvg(svg,{fitTo:{mode:'width',value:2160}}).render().asPng())}
